# -*- coding: utf-8 -*-
"""Sequence Modeling_AudioGeneration_Mahafuj.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N7Iy6JrNfngHtfSZigwqOUsqdhl6-caL
"""

# Sequence Modeling - Audible Music Generation
# Name: Md. Mahafuj Hossain


# ---------------------------------------------------------
# 1. Setup & Installs
# ---------------------------------------------------------
!apt-get install -qq fluidsynth
!pip install -q music21 midi2audio

import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
import random
import urllib.request
import os
import zipfile
import io
import matplotlib.pyplot as plt
from music21 import converter, instrument, note, chord, stream
from midi2audio import FluidSynth
from IPython.display import Audio, display

# Reproducibility
torch.manual_seed(42)
np.random.seed(42)
random.seed(42)

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f'Device : {device}')

# ---------------------------------------------------------
# 2. Dataset Preparation
# ---------------------------------------------------------
MIDI_ZIP_URL = "https://github.com/jukedeck/nottingham-dataset/archive/refs/heads/master.zip"
os.makedirs('/content/nottingham', exist_ok=True)

print("⬇ Downloading Nottingham MIDI dataset...")
with urllib.request.urlopen(MIDI_ZIP_URL) as r:
    zip_bytes = r.read()
with zipfile.ZipFile(io.BytesIO(zip_bytes)) as z:
    midi_files = [f for f in z.namelist() if f.endswith('.mid') or f.endswith('.midi')]
    for fname in midi_files[:80]:
        z.extract(fname, '/content/nottingham')

# Parse MIDI files into tokens
def get_notes():
    notes = []
    paths = []
    for root, dirs, files in os.walk('/content/nottingham'):
        for file in files:
            if file.endswith(".mid"):
                paths.append(os.path.join(root, file))

    print(f"Parsing {len(paths)} files...")
    for file in paths:
        midi = converter.parse(file)
        notes_to_parse = None
        try: # file has instrument parts
            s2 = instrument.partitionByInstrument(midi)
            notes_to_parse = s2.parts[0].recurse()
        except: # file has notes in a flat structure
            notes_to_parse = midi.flat.notes

        for element in notes_to_parse:
            if isinstance(element, note.Note):
                notes.append(str(element.pitch) + "_" + str(element.duration.quarterLength))
            elif isinstance(element, chord.Chord):
                notes.append('.'.join(str(n) for n in element.normalOrder) + "_" + str(element.duration.quarterLength))
    return notes

all_notes = get_notes()
pitchnames = sorted(set(item for item in all_notes))
n_vocab = len(pitchnames)
note_to_int = dict((note, number) for number, note in enumerate(pitchnames))

# Create sequences
sequence_length = 32
network_input = []
network_output = []

for i in range(0, len(all_notes) - sequence_length, 1):
    sequence_in = all_notes[i:i + sequence_length]
    sequence_out = all_notes[i + sequence_length]
    network_input.append([note_to_int[char] for char in sequence_in])
    network_output.append(note_to_int[sequence_out])

n_patterns = len(network_input)
network_input = torch.tensor(network_input, dtype=torch.long).to(device)
network_output = torch.tensor(network_output, dtype=torch.long).to(device)

# ---------------------------------------------------------
# 3. Model Definition (Vanilla RNN)
# ---------------------------------------------------------
class MusicRNN(nn.Module):
    def __init__(self, vocab_size, embedding_dim, hidden_dim):
        super(MusicRNN, self).__init__()
        self.embedding = nn.Embedding(vocab_size, embedding_dim)
        self.rnn = nn.RNN(embedding_dim, hidden_dim, batch_first=True)
        self.linear = nn.Linear(hidden_dim, vocab_size)

    def forward(self, x, hidden=None):
        embeds = self.embedding(x)
        output, hidden = self.rnn(embeds, hidden)
        output = self.linear(output[:, -1, :]) # Take last timestep
        return output, hidden

model = MusicRNN(n_vocab, 128, 256).to(device)
optimizer = optim.Adam(model.parameters(), lr=0.001)
criterion = nn.CrossEntropyLoss()

# ---------------------------------------------------------
# 4. Training
# ---------------------------------------------------------
epochs = 50
batch_size = 64
losses = []

print("Training started...")
for epoch in range(epochs):
    epoch_loss = 0
    permutation = torch.randperm(network_input.size(0))
    for i in range(0, network_input.size(0), batch_size):
        indices = permutation[i:i+batch_size]
        batch_x, batch_y = network_input[indices], network_output[indices]

        optimizer.zero_grad()
        output, _ = model(batch_x)
        loss = criterion(output, batch_y)
        loss.backward()
        optimizer.step()
        epoch_loss += loss.item()

    avg_loss = epoch_loss / (n_patterns / batch_size)
    losses.append(avg_loss)
    if (epoch+1) % 10 == 0:
        print(f"Epoch {epoch+1}/{epochs}, Loss: {avg_loss:.4f}")

plt.plot(losses)
plt.title("Training Loss")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.show()

# ---------------------------------------------------------
# 5. Generation
# ---------------------------------------------------------
model.eval()
start = np.random.randint(0, len(network_input)-1)
pattern = list(network_input[start].cpu().numpy())
prediction_output = []

print("Generating music...")
for note_index in range(100):
    prediction_input = torch.tensor([pattern], dtype=torch.long).to(device)
    prediction, _ = model(prediction_input)

    # Sample from distribution
    probs = torch.softmax(prediction, dim=1).cpu().detach().numpy()[0]
    index = np.random.choice(len(probs), p=probs)

    result = pitchnames[index]
    prediction_output.append(result)
    pattern.append(index)
    pattern = pattern[1:]

# Convert tokens back to MIDI
offset = 0
output_notes = []
for pattern in prediction_output:
    parts = pattern.split('_')
    note_pattern = parts[0]
    duration_pattern = float(parts[1])

    if ('.' in note_pattern) or note_pattern.isdigit():
        notes_in_chord = note_pattern.split('.')
        notes = []
        for current_note in notes_in_chord:
            new_note = note.Note(int(current_note))
            new_note.storedInstrument = instrument.Piano()
            notes.append(new_note)
        new_chord = chord.Chord(notes)
        new_chord.offset = offset
        new_chord.duration.quarterLength = duration_pattern
        output_notes.append(new_chord)
    else:
        new_note = note.Note(note_pattern)
        new_note.offset = offset
        new_note.storedInstrument = instrument.Piano()
        new_note.duration.quarterLength = duration_pattern
        output_notes.append(new_note)
    offset += duration_pattern

midi_stream = stream.Stream(output_notes)
midi_stream.write('midi', fp='generated_music.mid')

# ---------------------------------------------------------
# 6. Audio Playback
# ---------------------------------------------------------
FluidSynth("/usr/share/sounds/sf2/FluidR3_GM.sf2").midi_to_audio('generated_music.mid', 'generated_music.wav')
print("Generation Complete!")
display(Audio('generated_music.wav'))
display(Audio('generated_music.wav'))